---
### make a copy of this, call it secret.yaml (git ignored)
### and fill in the credentials

apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
data:
  username: #$ echo <docker-username> | base64
  password: #$ echo <docker-password> | base64
