---
### make a copy of this file in the o1_infra directory,
### call it docker-secret.yaml (git ignored)
### and fill in the credentials

apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
